src/main/java/com/ifam/dad/ejbweb/controller/ListarCidadeController.java
package com.ifam.dad.ejbweb.controller;

import com.ifam.dad.ejbweb.dao.CidadeDAO;
import com.ifam.dad.ejbweb.modelo.Cidade;
import static com.ifam.dad.ejbweb.util.FaceUtils.redirect;
import javax.annotation.PostConstruct;
import javax.inject.Inject;
import java.util.List;
import javax.inject.Named;

//@ViewScoped
@Named(value="listarCidadeController")
public class ListarCidadeController {


    @Inject
    CidadeDAO cidadeDAO;

    private List<Cidade> listaCidade;

    private String descricaoCidade;

    @PostConstruct
    public void init(){
        listaCidade = cidadeDAO.list();
    }

    public List<Cidade> getListaCidades() {
        if (descricaoCidade == null) {
            listaCidade = cidadeDAO.list();
        }
        else{
            listaCidade = cidadeDAO.listPorNome(descricaoCidade);
        }
        return listaCidade;
    }

    public String getDescricaoCidade() {
        return descricaoCidade;
    }

    public void setDescricaoCidade(String descricaoCidade) {
        this.descricaoCidade = descricaoCidade;
    }
    
    public String cadastrar(){
        return redirect("index");
    }
}

src/main/webapp/WEB-INF/templates/default.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title><ui:insert name="titulo">Título padrão</ui:insert> -
        Frameworks</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <ui:insert name="headers"/>
    <h:outputStylesheet library="css" name="bootstrap.min.css"/>
    <!--<h:outputStylesheet library="css" name="material.min.css"/>-->
    <!--<h:outputStylesheet library="css" name="ripples.min.css"/>-->
    <!--<h:outputStylesheet library="css" name="nprogress.css"/>-->
    <h:outputStylesheet library="css" name="style.css"/>
    <h:outputScript library="javax.faces" name="jsf.js" target="head"/>

</h:head>
<h:body>
    <!--<ui:include src="../componentes/header.xhtml"/>-->

    <div class="container">
        <!--<ui:debug hotkey="x" rendered="#{facesContext.application.projectStage eq 'Development'}"/>-->
        <h:messages id="messages" globalOnly="true"
                    styleClass="messages-alert" errorClass="alert alert-danger"
                    infoClass="alert alert-success" warnClass="alert alert-warning"
                    layout="list"/>
        <!--<h:messages/>-->
    </div>
    <ui:insert name="conteudo">
        Hello Default!
    </ui:insert>

    <ui:insert name="postjavascript">
    </ui:insert>
</h:body>
</html>







src/main/webapp/cidade/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="titulo">Cadastro Cidade</ui:define>

    <ui:define name="conteudo">
        <div class="container">
            <h:form>
                <div class="row center-block">
                    <div class="form-group col-xs-4">

                        <p>
                            <h:outputLabel for="nome" value="Nova Cidade"/>
                            <h:inputText styleClass="form-control" id="nome"
                                         value="#{controllerCidade.nome}"/>
                            <h:message for="nome" />
                            <br />
                            <h:commandButton value="Salvar Cidade" action="#{controllerCidade.cadastrar()}">
                                <f:ajax execute="@form" render="@all"/>
                            </h:commandButton>
                        </p>
                        <br />d
                    </div>
                </div>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/cidade/listar.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="titulo">Pesquisar</ui:define>

    <ui:define name="conteudo">
        <div class="container">
            <h:form>
                <div class="row center-block">
                    <div class="form-group col-xs-12">
                        <h:outputLabel for="nome" value="Nome"/>
                        <p>
                            <h:inputText styleClass="form-control" id="nome"
                                         value="#{listarCidadeController.descricaoCidade}"/>

                        </p>
                    </div>
                    <div class="form-group col-xs-12">
                        <h:commandButton
                                styleClass="btn btn-primary pull-right"
                                action="#{listarControllerCidade.getListaCidades}"
                                value="Pesquisar">
                            <f:ajax execute="@form" render=":container2"/>
                        </h:commandButton>
                        <h:link outcome="cadastrar" value="Novo" styleClass="btn btn-success"/>
                    </div>

                </div>
            </h:form>
            <h:form id="container2">


                <h:dataTable id="table" styleClass="table table-condensed table-hover"
                             value="#{listarCidadeController.listaCidades}"
                             var="cidade">
                    <h:column>
                        <f:facet name="header">Nome</f:facet>
                        #{cidade.nome}
                    </h:column>
                        <f:facet name="header">
                            Ação
                        </f:facet>
                        <h:commandButton value="remover"
                                         styleClass="btn btn-danger btn-sm"
                                         action="#{listarControllerCidade.remover(cidade)}">
                            <f:ajax execute="@this" render="notificacao @form"/>
                        </h:commandButton>
                </h:dataTable>
            </h:form>

        </div>
    </ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="titulo">Index</ui:define>

    <ui:define name="conteudo">
        <div class="container">
            <h:form>
                <div class="row center-block">
                    <div class="form-group col-xs-4">


                        <h:outputLabel for="nome" value="Nome"/>
                        <p><a href="cidade/">Cadastro de Cidade</a></p>
                        <p><a href="cidade/listar">Lista de Cidade</a></p>
                    </div>

                </div>
            </h:form>

        </div>
    </ui:define>
</ui:composition>

src/main/webapp/indexZero.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>